import { adminDb } from "@/lib/firebase/admin";

export interface PublicMarketingMetrics {
  usersCount: number;
  savedCollegesCount: number;
  matchingRunsCount: number;
  roadmapRunsCount: number;
  aiScoreCount: number;
}

export interface PublicSignalItem {
  title: string;
  value: string;
  note: string;
}

async function safeCollectionCount(collectionName: string): Promise<number> {
  try {
    const snap = await adminDb.collection(collectionName).count().get();
    return snap.data().count ?? 0;
  } catch {
    return 0;
  }
}

export async function getPublicMarketingMetrics(): Promise<PublicMarketingMetrics> {
  const [usersCount, savedCollegesCount, aiScoreCount] = await Promise.all([
    safeCollectionCount("users"),
    safeCollectionCount("savedColleges"),
    safeCollectionCount("aiScores"),
  ]);

  // Runs are stored as user subcollections; aggregate with collectionGroup.
  let matchingRunsCount = 0;
  let roadmapRunsCount = 0;
  try {
    const m = await adminDb.collectionGroup("matches").count().get();
    matchingRunsCount = m.data().count ?? 0;
  } catch {}
  try {
    const r = await adminDb.collectionGroup("roadmaps").count().get();
    roadmapRunsCount = r.data().count ?? 0;
  } catch {}

  return {
    usersCount,
    savedCollegesCount,
    matchingRunsCount,
    roadmapRunsCount,
    aiScoreCount,
  };
}

function fmt(n: number): string {
  return new Intl.NumberFormat("en-US").format(n);
}

export function toPublicSignals(m: PublicMarketingMetrics): PublicSignalItem[] {
  return [
    {
      title: "Active student accounts",
      value: fmt(m.usersCount),
      note: "Registered users in platform",
    },
    {
      title: "Saved colleges",
      value: fmt(m.savedCollegesCount),
      note: "Real college list items created",
    },
    {
      title: "Matching runs",
      value: fmt(m.matchingRunsCount),
      note: "Personalized matching executions",
    },
    {
      title: "Roadmaps generated",
      value: fmt(m.roadmapRunsCount),
      note: "Action plans generated by users",
    },
    {
      title: "AI score updates",
      value: fmt(m.aiScoreCount),
      note: "AI score calculations completed",
    },
  ];
}
